#pragma config(Sensor, in2,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in4,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, in5,    Potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl7,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           clawMotor,     tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port5,           armMotor,      tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                             	    - Triple Sensor Line Tracking -                                   *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program uses 3 VEX Line Follower Sensors to track a black line on a light(er) surface.       *|
|*  There is a two second pause at the beginning of the program.                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Lighting conditions, line darkness, and surface lightness change from place to place,       *|
|*        so the value of 'threshold' may need to be changed to better suit your environment.         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor  - Port 2     rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor  - Port 3     leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Analog - Port 1     lineFollowerRIGHT   VEX Light Sensor      Front-right, facing down          *|
|*    Analog - Port 2     lineFollowerCENTER  VEX Light Sensor      Front-center, facing down         *|
|*    Analog - Port 3     lineFollowerLEFT    VEX Light Sensor      Front-left, facing down           *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
void stop_motors()
{
	motor[leftMotor] = 0;
  motor[rightMotor] = 0;
  wait1Msec(100);
}
void turn()
{
	motor[rightMotor] = -35;
 	motor[leftMotor] = 35;
}
void claw_open()
{
	motor[clawMotor] = -60 ;
	wait1Msec(2000);
	motor[clawMotor] =0;
}
void claw_close()
{
	motor[clawMotor] = 60 ;
	wait1Msec(2000);
	motor[clawMotor] =0;
}
void lineDrive(int speed)
{
	int threshold = 2650;
	if(vexRT[Btn8U] == 1)
	{
		StopAllTasks();
	}
	if(SensorValue(lineFollowerRIGHT) > threshold)
    {
      // counter-steer right:
      motor[leftMotor]  = speed;
      motor[rightMotor] = 0;
    }
	if(SensorValue(lineFollowerCENTER) > threshold)
    {
      // go straight
      motor[leftMotor]  = speed;
      motor[rightMotor] = speed;
    }
	if(SensorValue(lineFollowerLEFT) > threshold)
    {
      // counter-steer left:
      motor[leftMotor]  = 0;
      motor[rightMotor] = speed;
    }
}
task main()
{
  wait1Msec(2000);          // The program waits for 2000 milliseconds before continuing.

        /* found by taking a reading on both DARK and LIGHT    */
                            /* surfaces, adding them together, then dividing by 2. */

  while(SensorValue(Potentiometer) < 1050)
  {
  	motor[armMotor] = -30;
  }
  motor[armMotor] = 0;

  while(SensorValue(sonarSensor) > 25 || SensorValue(sonarSensor) == -1)		// Loop while robot's Ultrasonic sensor is further than 20 inches away from an object
	{
		int speed = 35;
    lineDrive(speed);
  }
  stop_motors();
  while(SensorValue(Potentiometer) > 400)
  {
  	motor[armMotor] = 10;
  }
  motor[armMotor] = 0;
  claw_open();

  while(SensorValue(sonarSensor) > 9  || SensorValue(sonarSensor) == -1)		// Loop while robot's Ultrasonic sensor is further than 20 inches away from an object
	{

		int speed = 35;
		lineDrive(speed);
	}

  stop_motors();

  claw_close();
	while(SensorValue(Potentiometer) < 1250)
  {
  	motor[armMotor] = -45;
  }
  motor[armMotor] = 0;
 	turn();
 	wait1Msec(3000);
 	stop_motors();
 	int threshold = 2650;
 	while(SensorValue(lineFollowerCENTER) < threshold)
 	{
    turn();
	}
	while(SensorValue(sonarSensor) > 9  || SensorValue(sonarSensor) == -1)		// Loop while robot's Ultrasonic sensor is further than 20 inches away from an object
	{
		int speed = 35;
    lineDrive(speed);
  }
  stop_motors();
  while(SensorValue(Potentiometer) > 600)
  {
  	motor[armMotor] = 20;
  }
  motor[armMotor] =0;
  claw_open();
}
