#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                              - Forward for Distance with Encoders -                                *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to move forward for 5 rotations of the left shaft encoder.       *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" model, but may not be needed for all robot configurations.                      *|
|*    2)  Whichever encoder is being used for feedback should be cleared just before it starts        *|
|*        counting by using the "SensorValue(encoder) = 0;".  This helps ensure consistancy.          *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Shaft Encoder     Right side                        *|
|*    Digital - Port 3,4  leftEncoder         VEX Shaft Encoder     Left side                         *|
\*----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
// gerum void fyrir a keyra fram og kollum  i breytuna
void Halfurmetri()
{
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;


	while(SensorValue[leftEncoder] < 500)  // While less than 5 rotations on the leftEncoder... 320 hringur
		{
			if(vexRT[Btn8U] == 1)
			{
				StopAllTasks();
			}
	  	if(SensorValue[rightEncoder] == SensorValue[leftEncoder]) // If rightEncoder has counted the same amount as leftEncoder:
			{
				// Move Forward
				motor[rightMotor] = 80;		    // Right Motor is run at power level 80
				motor[leftMotor]  = 80;		    // Left Motor is run at power level 80
			}
			else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])	// If rightEncoder has counted more encoder counts
			{
				// Turn slightly right
				motor[rightMotor] = 60;		    // Right Motor is run at power level 60
				motor[leftMotor]  = 80;		    // Left Motor is run at power level 80
			}
			else	// Only runs if leftEncoder has counted more encoder counts
			{
				// Turn slightly left
				motor[rightMotor] = 80;		    // Right Motor is run at power level 80
				motor[leftMotor]  = 60;		    // Left Motor is run at power level 60
			}
		}
}

task main()
{





	Halfurmetri();

	wait1Msec(200);

	motor[leftMotor] = 60;
  motor[rightMotor] = -60;
  wait1Msec(850);

	Halfurmetri();

	wait1Msec(200);

	motor[leftMotor] = -60;
  motor[rightMotor] = 60;
  wait1Msec(850);

	Halfurmetri();

	wait1Msec(200);

	motor[leftMotor] = -60;
  motor[rightMotor] = 60;
  wait1Msec(850);

  Halfurmetri();


}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
